### ISSUE TITLE
Must web publications be available offline?

### ISSUE THREAD

**Issue by dauwhe** [w3c/dpub-pwp#41]
Opening this as an issue to have a place for discussion. The current WP draft states:

>A Web Publication must be available and functional while the user is offline. A user should, as much as possible, have a seamless experience of interacting with a Web Publication regardless of their network connection. We make no distinction between online and offline when defining web publications.

I don't think we should change must to should in the first sentence. To me, a fundamental aspect of a publication is that it has some sort of permanent existence—it doesn't just go away depending on circumstances. Trying to retain that sense of permanence in a digital world is important. 

There's also significant concern in the ebook community (voiced, for example, by Fran Toolan) that "the web" doesn't care about offline, and that the IDPF+W3C combination means that offline use cases will be given less weight.

**Comment by BillKasdorf** [comment]
+1

Bill Kasdorf

VP and Principal Consultant | Apex CoVantage

p:

734-904-6252  m:   734-904-6252

ISNI: http://isni.org/isni/0000000116490786
ORCiD: https://orcid.org/0000-0001-7002-4786<https://orcid.org/0000-0001-7002-4786?lang=en>

**Comment by GarthConboy** [comment]
Thanks Dave,

I'm completely with you regarding the importance of offline.

Though, I somewhat think of WP's as generally served in an online
environment and PWP's as packaged for offline use.  Does the following help
or hurt:

A Web Publication must be [able to be made] available and functional while
the user is offline. A user should, as much as possible, have a seamless
experience of interacting with a Web Publication regardless of their
network connection. We make no distinction between online and offline when
defining web publications.

Best,
   Garth

**Comment by iherman** [comment]
Admin: this was also discussed on the [call on febr. 13th](https://www.w3.org/2017/02/13-dpub-minutes.html#mozTocId352742)

**Comment by iherman** [comment]
> On 27 Feb 2017, at 17:03, GarthConboy <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Thanks Dave,
> 
> I'm completely with you regarding the importance of offline.
> 
> Though, I somewhat think of WP's as generally served in an online
> environment and PWP's as packaged for offline use.

Although that statement is not necessarily reflected in what you write below as a text proposal, I do not agree with this statement… The idea is that I do not _necessarily_ have to put things into a package to be able to read it offline. It should "just" happen, as actually shown on the experimentation of both Dave and Hadrien. Or, to take another example:

https://hpbn.co/ <https://hpbn.co/>

is a complete book that, once a browser 'sees' it, can be enjoyed both online and offline.

All these examples use various, though not completely dissimilar tricks to achieve that and producing those books require some non-trivial efforts. The goal would be to make the production of such books easy through standards...



> Does the following help
> or hurt:
> 
> A Web Publication must be [able to be made] available and functional while
> the user is offline. A user should, as much as possible, have a seamless
> experience of interacting with a Web Publication regardless of their
> network connection. We make no distinction between online and offline when
> defining web publications.
> 

Note that we are repeating our discussion from [one of the last calls](https://www.w3.org/2017/02/13-dpub-minutes.html#mozTocId352742 <https://www.w3.org/2017/02/13-dpub-minutes.html#mozTocId352742>). I believe what we agreed upon is that, _in the PWP draft_, it is not necessary to be overly succinct, and that instead of trying to put everything into 1-2 sentence, we would add some explanation of what we mean… It is just that we did not come around yet to see that extra text.

**Comment by TzviyaSiegman** [comment]
Hello strangers! It seems to m that we are re-visiting very old discussions. I think we reached some level of consensus at tpac [1, 2]. This is what we were calling the "p" problem. We had some debate about what the p should stand for "portable" or "packaged". There was also much debate about what "offline" means. @GarthConboy had a nifty grid, and @BorisAnthony recommended a discussion of basic terms and definitions. maybe we need to return to that so this can be completed? 

[1] https://www.w3.org/2016/09/19-dpub-minutes.html#mozTocId850580
[1] https://www.w3.org/2016/09/19-dpub-minutes.html#mozTocId509920

**Comment by GarthConboy** [comment]
I believe that Ivan and Tzviya are, of course, correct -- just continuing
to look for middle ground as this topic hasn't died yet.

Perhaps the expected proposed text for the charter from Dave/Leonard will
be perfectly agreeable to all in 30 min!  :-)

Best,
   Garth

**Comment by iherman** [comment]
> On 27 Feb 2017, at 17:30, GarthConboy <notifications@github.com> wrote:
> 
> I believe that Ivan and Tzviya are, of course, correct -- just continuing
> to look for middle ground as this topic hasn't died yet.

I know I often get a mind-melt with Tzviya, but I did not realize that was also the case while she is on maternity leave:-)

**Comment by dauwhe** [comment]
Closed per resolution of 2/27/17 call
